#!/usr/bin/env bash
# bash script

	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit 0;" SIGTERM
	trap "rm /var/run/myscript.pid; exit 0;" SIGQUIT
	trap "echo 'Y U no love me?!'" SIGINT

	touch /var/run/myscript.pid
	echo "$$" > /car/run/myscript.pid

	while true
	do
		echo 'To infinity and beyond'
	done
