#!/usr/bin/env bash
# File: 100-read_and_cut.sh


file="/etc/passwd"


while read -r line
do
    username=$(echo "$line" | cut -d ':' -f1)
    userid=$(echo "$line" | cut -d ':' -f3)
    homedir=$(echo "$line" | cut -d ':' -f6)
    echo "$username:$userid:$homedir"
done < "$file"
