#!/usr/bin/env bash
# File: 101-tell_the_story_of_passwd.sh


file="/etc/passwd"

while IFS=: read -r USERNAME PASSWORD USER_ID GROUP_ID INFO HOME_DIRECTORY COMMAND_SHELL
do
    echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode &$PASSWORD, more info about the user here: $USERNAME"
done < "$file"
