#!/usr/bin/env bash
# File: while_best_school.sh


counter=0

while [[ $counter -lt 10 ]]
do
    if [[ $counter -eq 9 ]]
    then
        echo 'Hi'
    fi

    echo 'Best School'
    ((counter++))
done
