#!/usr/bin/env bash
# File: 7-clock.sh

hours=0
minutes=1

while [[ $hours -lt 13 ]]
do

    echo "Hour: $hours"

    while [[ $minutes -lt 60 ]]
    do
        echo $minutes

        ((minutes++))
    done

    ((hours++))

    minutes=1

done
