#!/usr/bin/env bash
# File: 9-to_file_or_not_to_file.sh


file="school"

if [[ -e "$file" ]]
then
    echo "school file exists"

    if [[ -s "$file" ]]
    then
        echo "school file is not empty"

    else

        echo "school file is empty"
    fi

    if [[ -f "$file" ]]
    then
        echo "school file is a regular file"
    fi



else
    echo "School file does not exist"
fi
